/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testmyproject_NDKTool */

//#ifndef _Included_com_example_testmyproject_NDKTool
//#define _Included_com_example_testmyproject_NDKTool
#ifdef __cplusplus
extern "C" {
#endif

extern "C"
JNIEXPORT jstring JNICALL Java_com_example_testmyproject_NDKTool_callNative
  (JNIEnv *, jobject, jstring);
#ifdef __cplusplus
}
#endif
